version: 1.0.{build}
configuration: Release
platform: x64
init:
- ps: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: >-
    Webpicmd /install /products:"MicrosoftAzure-ServiceFabric-VS2015-2_1" /AcceptEULA


    $env:PATH="C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;$env:PATH";
before_build:
- ps: nuget restore $env:APPVEYOR_BUILD_FOLDER\DictionaryApp.sln
build:
  project: DictionaryApp.sln
  verbosity: minimal
after_build:
- ps: msbuild DictionaryApp\DictionaryApp.sfproj /t:Package /p:Configuration=Release /p:PlatformTarget=x64